
package com.gapblue.web.stubs.accountresource;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesAccountResourceService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesAccountResourceService {


    /**
     * 
     * @param sAccountResourceId
     * @return
     *     returns com.gapblue.web.stubs.accountresource.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "getSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetSalesAccountResource")
    @ResponseWrapper(localName = "getSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetSalesAccountResourceResponse")
    public SalesAccountResource getSalesAccountResource(
        @WebParam(name = "sAccountResourceId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        long sAccountResourceId)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @return
     *     returns com.gapblue.web.stubs.accountresource.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/createSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "createSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.CreateSalesAccountResource")
    @ResponseWrapper(localName = "createSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.CreateSalesAccountResourceResponse")
    public SalesAccountResource createSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @return
     *     returns com.gapblue.web.stubs.accountresource.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/updateSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "updateSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.UpdateSalesAccountResource")
    @ResponseWrapper(localName = "updateSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.UpdateSalesAccountResourceResponse")
    public SalesAccountResource updateSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/deleteSalesAccountResource")
    @RequestWrapper(localName = "deleteSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.DeleteSalesAccountResource")
    @ResponseWrapper(localName = "deleteSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.DeleteSalesAccountResourceResponse")
    public void deleteSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.gapblue.web.stubs.accountresource.SalesAccountResource>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/findSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "findSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.FindSalesAccountResource")
    @ResponseWrapper(localName = "findSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.FindSalesAccountResourceResponse")
    public List<SalesAccountResource> findSalesAccountResource(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param sAccountResourceId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "getSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetSalesAccountResourceAsync")
    public void getSalesAccountResourceAsync(
        @WebParam(name = "sAccountResourceId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        long sAccountResourceId);

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/updateSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "updateSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.UpdateSalesAccountResourceAsync")
    public void updateSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/deleteSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.DeleteSalesAccountResourceAsync")
    public void deleteSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/findSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "findSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.FindSalesAccountResourceAsync")
    public void findSalesAccountResourceAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        FindControl findControl);

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/createSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "createSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.CreateSalesAccountResourceAsync")
    public void createSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.gapblue.web.stubs.accountresource.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.gapblue.web.stubs.accountresource.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/types/", className = "com.gapblue.web.stubs.accountresource.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
