
package com.gapblue.web.stubs.accountresource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalesAccountResourceService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/", wsdlLocation = "https://eeal-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/SalesAccountResourceService?WSDL")
public class SalesAccountResourceService_Service
    extends Service
{

    private final static URL SALESACCOUNTRESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESACCOUNTRESOURCESERVICE_EXCEPTION;
    private final static QName SALESACCOUNTRESOURCESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/", "SalesAccountResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eeal-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/SalesAccountResourceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESACCOUNTRESOURCESERVICE_WSDL_LOCATION = url;
        SALESACCOUNTRESOURCESERVICE_EXCEPTION = e;
    }

    public SalesAccountResourceService_Service() {
        super(__getWsdlLocation(), SALESACCOUNTRESOURCESERVICE_QNAME);
    }

    public SalesAccountResourceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESACCOUNTRESOURCESERVICE_QNAME, features);
    }

    public SalesAccountResourceService_Service(URL wsdlLocation) {
        super(wsdlLocation, SALESACCOUNTRESOURCESERVICE_QNAME);
    }

    public SalesAccountResourceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESACCOUNTRESOURCESERVICE_QNAME, features);
    }

    public SalesAccountResourceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesAccountResourceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalesAccountResourceService
     */
    @WebEndpoint(name = "SalesAccountResourceServiceSoapHttpPort")
    public SalesAccountResourceService getSalesAccountResourceServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/", "SalesAccountResourceServiceSoapHttpPort"), SalesAccountResourceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesAccountResourceService
     */
    @WebEndpoint(name = "SalesAccountResourceServiceSoapHttpPort")
    public SalesAccountResourceService getSalesAccountResourceServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesAccountResourceService/", "SalesAccountResourceServiceSoapHttpPort"), SalesAccountResourceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESACCOUNTRESOURCESERVICE_EXCEPTION!= null) {
            throw SALESACCOUNTRESOURCESERVICE_EXCEPTION;
        }
        return SALESACCOUNTRESOURCESERVICE_WSDL_LOCATION;
    }

}
