package com.gapblue.salesdashboard.writer;

import java.util.List;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.ExitStatus;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.database.ItemPreparedStatementSetter;
import org.springframework.batch.item.database.JdbcBatchItemWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Configuration;

import com.gapblue.salesdashboard.db.OppPreparedStatementSetter;
import com.gapblue.salesdashboard.db.RevenuePreparedStatementSetter;
import com.gapblue.salesdashboard.util.SalesDashboardUtils;
import com.gapblue.web.stubs.opportunity.Opportunity;
import com.gapblue.web.stubs.opportunity.Revenue;

@Configuration
public class DatabaseOpportunityWriter implements ItemWriter<Opportunity>, StepExecutionListener {
	private static final Logger LOGGER = LoggerFactory.getLogger(DatabaseOpportunityWriter.class);

	// 13-03-2018 : Query changed to add DatasourceRefresh fields
	private static final String QUERY_INSERT_OPPORTUNITY = "MERGE INTO XXINV_OPPORTUNITY a "
			+ "USING (SELECT ? CREATIONDATE, ? CURRENCYCODE, ? NAME,? optyid, ? optynumber, ? STATUSCODE,? TARGETPARTYNAME,? SALESMETHOD,"
			+ "? SALESSTAGE, ? AVERAGEDAYSATSTAGE,? PHASECD,? STAGESTATUSCD, ? EFFECTIVEDATE, ? REVENUE,? REVENUETYPE, ? REVNID, ? PRIMARYCONTACTPARTYNAME, "
			+ "? ACCOUNTNUMBER,? PARTYNAME, ? FORMATTEDADDRESS,? CITY, ? COUNTRY, ? POSTALCODE,? STATE, ? OPTYCREATIONDATE,? EXPECTAMOUNT, ? PARTYUNIQUENAME, "
			+ "? OPTYCREATEDBY, ? CRMREVENUE,? PARTYTYPE,? SALESCHANNELCD,? PRIMARYORGANIZATIONNAME,? APPROVALSTATUS_C,? PARENTENDCUSTOMER_C,? MARKETSEGMENT_C,"
			+ "? SUBSEGMENT_C,? PROJECTNAME_C,? PROJECTSTARTDATE_C,? OPPORTUNITYTYPE_C,? EVALPARTREQUESTEDDATE_C,? TARGETDESIGNINDATE_C,? TARGETDESIGNWINDATE_C,"
			+ "? TARGETPRODUCTIONDATE_C,? EVALUATIONCOMPLETEDATE_C,? ACTUALDESIGNINDATE_C,? ACTUALDESIGNWINDATE_C,? ACTUALPRODUCTIONSTARTDATE_C,? OPPORTUNITY_C,"
			+ "? LIFETIMEREVENUE_C,? MARKETSEGMENT1_C,? SUBSEGMENT1_C,? ENDCUSTOMER_C,? ENDCUSTOMERREGION_C,? ENDCUSTOMERSTATE_C,? ENDCUSTOMERCOUNTRY_C,? ORGANIZATION,"
			+ "? WINPROB ,? MARKETINGPROBABILITY_C ,? CLOSEDORCANCELLEDDATE_C ,? REASON_C ,? REASONDESCRIPTION_C ,? COMPETITORINFO_C ,"
			+ "? FORECAST_C ,? OPPORTUNITYOWNER_C ,? EVALPARTRECEIVED_C ,? CUSTOMERAPPROVEDQUOTE_C , ? DEALREGISTRATION_C , ? SELECTDEALREP2_C ,? DEALREGID2_C ,"
			+ "? APPLICATION_C ,? OPPORTUNITYLIFETIMEYEARS_C ,? PROJECTDESCRIPTION_C ,? SALESCOMMENT_C , ? PRODUCTMANAGERCOMMENTS , ? HELPSTATUS_C ,"
			+ "? HELPNEEDEDFROM_C ,? DATEOFHELPREQUEST_C , ? CRITICALACTIONITEMSMILESTONES , ? RISKCHALLENGES_C ,? DESIGNINREGIONALMGRAPPROVED_C ,"
			+ "? DESIGNINREGIONALMGRAPPROVALDT ,? DESIGNWINREGIONALMGRAPPROVED ,? DESIGNWINREGIONALMGRAPPROVALDT ,? DESIGNWINVPSALESAPPROVED_C ,"
			+ "? DESIGNWINVPSALESAPPROVALDATE , ? DESIGNWINMARKETINGAPPROVED_C ,? DESIGNWINMARKETINGAPPROVALDATE ,? MPVPSALESAPPROVED_C ,"
			+ "? MPVPSALESAPPROVALDATE_C , ? LOSTVPSALESAPPROVED_C , ? LOSTVPSALESAPPROVALDATE_C , ? PART_C ,? BU_C ,? ANNUALUNITVOLUME_C ,"
			+ "? ASP_C ,? ANNUALREVENUE , ? EXPECTEDREVENUE_C , ? LASTUPDATEDBY , ? LASTUPDATEDATE ,? PRODUCTTYPE FROM dual) incoming "
			+ "ON (a.optyid = incoming.optyid ) " + "WHEN MATCHED THEN "
			+ "UPDATE SET a.CREATIONDATE=incoming.CREATIONDATE,a.CURRENCYCODE=incoming.CURRENCYCODE,a.NAME=incoming.NAME,"
			+ "a.OPTYNUMBER=incoming.OPTYNUMBER,a.STATUSCODE=incoming.STATUSCODE,a.TARGETPARTYNAME=incoming.TARGETPARTYNAME,a.SALESMETHOD=incoming.SALESMETHOD,"
			+ "a.SALESSTAGE=incoming.SALESSTAGE,a.AVERAGEDAYSATSTAGE=incoming.AVERAGEDAYSATSTAGE,a.PHASECD=incoming.PHASECD,a.STAGESTATUSCD=incoming.STAGESTATUSCD,"
			+ "a.EFFECTIVEDATE=incoming.EFFECTIVEDATE,a.REVENUE=incoming.REVENUE,a.REVENUETYPE=incoming.REVENUETYPE,a.REVNID=incoming.REVNID,"
			+ "a.PRIMARYCONTACTPARTYNAME=incoming.PRIMARYCONTACTPARTYNAME,a.ACCOUNTNUMBER=incoming.ACCOUNTNUMBER,a.PARTYNAME=incoming.PARTYNAME,"
			+ "a.FORMATTEDADDRESS=incoming.FORMATTEDADDRESS,a.CITY=incoming.CITY,a.COUNTRY=incoming.COUNTRY,a.POSTALCODE=incoming.POSTALCODE,a.STATE=incoming.STATE,"
			+ "a.OPTYCREATIONDATE=incoming.OPTYCREATIONDATE,a.EXPECTAMOUNT=incoming.EXPECTAMOUNT,a.PARTYUNIQUENAME=incoming.PARTYUNIQUENAME,"
			+ "a.OPTYCREATEDBY=incoming.OPTYCREATEDBY,a.CRMREVENUE=incoming.CRMREVENUE,a.PARTYTYPE=incoming.PARTYTYPE,a.SALESCHANNELCD=incoming.SALESCHANNELCD,"
			+ "a.PRIMARYORGANIZATIONNAME=incoming.PRIMARYORGANIZATIONNAME,a.APPROVALSTATUS_C=incoming.APPROVALSTATUS_C,a.PARENTENDCUSTOMER_C=incoming.PARENTENDCUSTOMER_C,"
			+ "a.MARKETSEGMENT_C=incoming.MARKETSEGMENT_C,a.SUBSEGMENT_C=incoming.SUBSEGMENT_C,a.PROJECTNAME_C=incoming.PROJECTNAME_C,"
			+ "a.PROJECTSTARTDATE_C=incoming.PROJECTSTARTDATE_C,a.OPPORTUNITYTYPE_C=incoming.OPPORTUNITYTYPE_C,a.EVALPARTREQUESTEDDATE_C=incoming.EVALPARTREQUESTEDDATE_C,"
			+ "a.TARGETDESIGNINDATE_C=incoming.TARGETDESIGNINDATE_C,a.TARGETDESIGNWINDATE_C=incoming.TARGETDESIGNWINDATE_C,a.TARGETPRODUCTIONDATE_C=incoming.TARGETPRODUCTIONDATE_C,"
			+ "a.EVALUATIONCOMPLETEDATE_C=incoming.EVALUATIONCOMPLETEDATE_C,a.ACTUALDESIGNINDATE_C=incoming.ACTUALDESIGNINDATE_C,a.ACTUALDESIGNWINDATE_C=incoming.ACTUALDESIGNWINDATE_C,"
			+ "a.ACTUALPRODUCTIONSTARTDATE_C=incoming.ACTUALPRODUCTIONSTARTDATE_C,a.OPPORTUNITY_C=incoming.OPPORTUNITY_C,a.LIFETIMEREVENUE_C=incoming.LIFETIMEREVENUE_C,a.MARKETSEGMENT1_C=incoming.MARKETSEGMENT1_C,"
			+ "a.SUBSEGMENT1_C=incoming.SUBSEGMENT1_C,a.ENDCUSTOMER_C=incoming.ENDCUSTOMER_C,"
			+ "a.ENDCUSTOMERREGION_C=incoming.ENDCUSTOMERREGION_C,"
			+ "a.ENDCUSTOMERSTATE_C=incoming.ENDCUSTOMERSTATE_C,a.ENDCUSTOMERCOUNTRY_C=incoming.ENDCUSTOMERCOUNTRY_C,a.ORGANIZATION=incoming.ORGANIZATION, "
			+ "a.WINPROB=incoming.WINPROB ,a.MARKETINGPROBABILITY_C=incoming.MARKETINGPROBABILITY_C ,a.CLOSEDORCANCELLEDDATE_C=incoming.CLOSEDORCANCELLEDDATE_C ,a.REASON_C=incoming.REASON_C, "
			+ "a.REASONDESCRIPTION_C=incoming.REASONDESCRIPTION_C ,a.COMPETITORINFO_C=incoming.COMPETITORINFO_C,a.FORECAST_C=incoming.FORECAST_C "
			+ ",a.OPPORTUNITYOWNER_C=incoming.OPPORTUNITYOWNER_C ,a.EVALPARTRECEIVED_C=incoming.EVALPARTRECEIVED_C "
			+ ",a.CUSTOMERAPPROVEDQUOTE_C=incoming.CUSTOMERAPPROVEDQUOTE_C ,"
			+ "a.DEALREGISTRATION_C=incoming.DEALREGISTRATION_C "
			+ ",a.SELECTDEALREP2_C=incoming.SELECTDEALREP2_C ,a.DEALREGID2_C=incoming.DEALREGID2_C ,a.APPLICATION_C=incoming.APPLICATION_C "
			+ ",a.OPPORTUNITYLIFETIMEYEARS_C=incoming.OPPORTUNITYLIFETIMEYEARS_C , a.PROJECTDESCRIPTION_C=incoming.PROJECTDESCRIPTION_C "
			+ ",a.SALESCOMMENT_C=incoming.SALESCOMMENT_C ,"
			+ "a.PRODUCTMANAGERCOMMENTS=incoming.PRODUCTMANAGERCOMMENTS ,a.HELPSTATUS_C=incoming.HELPSTATUS_C "
			+ ",a.HELPNEEDEDFROM_C=incoming.HELPNEEDEDFROM_C ,a.DATEOFHELPREQUEST_C=incoming.DATEOFHELPREQUEST_C "
			+ ",a.CRITICALACTIONITEMSMILESTONES=incoming.CRITICALACTIONITEMSMILESTONES ,a.RISKCHALLENGES_C=incoming.RISKCHALLENGES_C "
			+ ",a.DESIGNINREGIONALMGRAPPROVED_C=incoming.DESIGNINREGIONALMGRAPPROVED_C ,a.DESIGNINREGIONALMGRAPPROVALDT=incoming.DESIGNINREGIONALMGRAPPROVALDT ,"
			+ "a.DESIGNWINREGIONALMGRAPPROVED=incoming.DESIGNWINREGIONALMGRAPPROVED , a.DESIGNWINREGIONALMGRAPPROVALDT=incoming.DESIGNWINREGIONALMGRAPPROVALDT, "
			+ "a.DESIGNWINVPSALESAPPROVED_C=incoming.DESIGNWINVPSALESAPPROVED_C ,a.DESIGNWINVPSALESAPPROVALDATE=incoming.DESIGNWINVPSALESAPPROVALDATE , "
			+ "a.DESIGNWINMARKETINGAPPROVED_C=incoming.DESIGNWINMARKETINGAPPROVED_C ,a.DESIGNWINMARKETINGAPPROVALDATE=incoming.DESIGNWINMARKETINGAPPROVALDATE , "
			+ "a.MPVPSALESAPPROVED_C=incoming.MPVPSALESAPPROVED_C ,a.MPVPSALESAPPROVALDATE_C=incoming.MPVPSALESAPPROVALDATE_C ,"
			+ "a.LOSTVPSALESAPPROVED_C =incoming.LOSTVPSALESAPPROVED_C, a.LOSTVPSALESAPPROVALDATE_C =incoming.LOSTVPSALESAPPROVALDATE_C, a.PART_C=incoming.PART_C , "
			+ "a.BU_C=incoming.BU_C ,a.ANNUALUNITVOLUME_C =incoming.ANNUALUNITVOLUME_C, a.ASP_C=incoming.ASP_C ,a.ANNUALREVENUE=incoming.ANNUALREVENUE , "
			+ "a.EXPECTEDREVENUE_C=incoming.EXPECTEDREVENUE_C,a.LASTUPDATEDBY =incoming.LASTUPDATEDBY,a.LASTUPDATEDATE=incoming.LASTUPDATEDATE , "
			+ "a.PRODUCTTYPE=incoming.PRODUCTTYPE " +

			"WHEN NOT MATCHED THEN "
			+ "INSERT (CREATIONDATE,CURRENCYCODE,NAME,OPTYID,OPTYNUMBER,STATUSCODE,TARGETPARTYNAME,SALESMETHOD,SALESSTAGE,AVERAGEDAYSATSTAGE,PHASECD,STAGESTATUSCD,"
			+ "EFFECTIVEDATE,REVENUE,REVENUETYPE,REVNID,PRIMARYCONTACTPARTYNAME,ACCOUNTNUMBER,PARTYNAME,FORMATTEDADDRESS,CITY,COUNTRY,POSTALCODE,STATE"
			+ ",OPTYCREATIONDATE,EXPECTAMOUNT,PARTYUNIQUENAME,OPTYCREATEDBY,CRMREVENUE,PARTYTYPE,SALESCHANNELCD,PRIMARYORGANIZATIONNAME,APPROVALSTATUS_C"
			+ ",PARENTENDCUSTOMER_C,MARKETSEGMENT_C,SUBSEGMENT_C,PROJECTNAME_C,PROJECTSTARTDATE_C,OPPORTUNITYTYPE_C,EVALPARTREQUESTEDDATE_C,TARGETDESIGNINDATE_C"
			+ ",TARGETDESIGNWINDATE_C,TARGETPRODUCTIONDATE_C,EVALUATIONCOMPLETEDATE_C,ACTUALDESIGNINDATE_C,ACTUALDESIGNWINDATE_C,ACTUALPRODUCTIONSTARTDATE_C,"
			+ "OPPORTUNITY_C,LIFETIMEREVENUE_C,MARKETSEGMENT1_C,SUBSEGMENT1_C,ENDCUSTOMER_C,ENDCUSTOMERREGION_C,ENDCUSTOMERSTATE_C,ENDCUSTOMERCOUNTRY_C,ORGANIZATION,"
			+ "WINPROB , MARKETINGPROBABILITY_C ,CLOSEDORCANCELLEDDATE_C , REASON_C ,REASONDESCRIPTION_C ,COMPETITORINFO_C , FORECAST_C ,OPPORTUNITYOWNER_C ,"
			+ "EVALPARTRECEIVED_C ,CUSTOMERAPPROVEDQUOTE_C , DEALREGISTRATION_C ,SELECTDEALREP2_C , DEALREGID2_C ,APPLICATION_C , OPPORTUNITYLIFETIMEYEARS_C ,"
			+ "PROJECTDESCRIPTION_C ,SALESCOMMENT_C ,PRODUCTMANAGERCOMMENTS ,HELPSTATUS_C ,HELPNEEDEDFROM_C ,DATEOFHELPREQUEST_C ,CRITICALACTIONITEMSMILESTONES ,"
			+ "RISKCHALLENGES_C ,	DESIGNINREGIONALMGRAPPROVED_C , DESIGNINREGIONALMGRAPPROVALDT ,	DESIGNWINREGIONALMGRAPPROVED ,DESIGNWINREGIONALMGRAPPROVALDT , "
			+ "DESIGNWINVPSALESAPPROVED_C , DESIGNWINVPSALESAPPROVALDATE , DESIGNWINMARKETINGAPPROVED_C , DESIGNWINMARKETINGAPPROVALDATE , MPVPSALESAPPROVED_C ,"
			+ "MPVPSALESAPPROVALDATE_C ,LOSTVPSALESAPPROVED_C ,LOSTVPSALESAPPROVALDATE_C ,PART_C ,BU_C ,ANNUALUNITVOLUME_C ,ASP_C , ANNUALREVENUE , EXPECTEDREVENUE_C ,"
			+ "LASTUPDATEDBY ,LASTUPDATEDATE ,PRODUCTTYPE )"
			+ "VALUES (incoming.CREATIONDATE,incoming.CURRENCYCODE,incoming.NAME,incoming.OPTYID,incoming.OPTYNUMBER,incoming.STATUSCODE,incoming.TARGETPARTYNAME,incoming.SALESMETHOD,incoming.SALESSTAGE,incoming.AVERAGEDAYSATSTAGE,incoming.PHASECD,incoming.STAGESTATUSCD,"
			+ "incoming.EFFECTIVEDATE,incoming.REVENUE,incoming.REVENUETYPE,incoming.REVNID,incoming.PRIMARYCONTACTPARTYNAME,incoming.ACCOUNTNUMBER,incoming.PARTYNAME,incoming.FORMATTEDADDRESS,incoming.CITY,incoming.COUNTRY,incoming.POSTALCODE,incoming.STATE"
			+ ",incoming.OPTYCREATIONDATE,incoming.EXPECTAMOUNT,incoming.PARTYUNIQUENAME,incoming.OPTYCREATEDBY,incoming.CRMREVENUE,incoming.PARTYTYPE,incoming.SALESCHANNELCD,incoming.PRIMARYORGANIZATIONNAME,incoming.APPROVALSTATUS_C"
			+ ",incoming.PARENTENDCUSTOMER_C,incoming.MARKETSEGMENT_C,incoming.SUBSEGMENT_C,incoming.PROJECTNAME_C,incoming.PROJECTSTARTDATE_C,incoming.OPPORTUNITYTYPE_C,incoming.EVALPARTREQUESTEDDATE_C,incoming.TARGETDESIGNINDATE_C"
			+ ",incoming.TARGETDESIGNWINDATE_C,incoming.TARGETPRODUCTIONDATE_C,incoming.EVALUATIONCOMPLETEDATE_C,incoming.ACTUALDESIGNINDATE_C,incoming.ACTUALDESIGNWINDATE_C,incoming.ACTUALPRODUCTIONSTARTDATE_C,"
			+ "incoming.OPPORTUNITY_C,incoming.LIFETIMEREVENUE_C,incoming.MARKETSEGMENT1_C,incoming.SUBSEGMENT1_C,incoming.ENDCUSTOMER_C,incoming.ENDCUSTOMERREGION_C,incoming.ENDCUSTOMERSTATE_C,incoming.ENDCUSTOMERCOUNTRY_C,incoming.ORGANIZATION,"
			+ "incoming.WINPROB ,incoming.MARKETINGPROBABILITY_C ,incoming.CLOSEDORCANCELLEDDATE_C ,incoming.REASON_C ,incoming.REASONDESCRIPTION_C ,incoming.COMPETITORINFO_C ,incoming.FORECAST_C ,incoming.OPPORTUNITYOWNER_C ,incoming.EVALPARTRECEIVED_C ,"
			+ "incoming.CUSTOMERAPPROVEDQUOTE_C ,incoming.DEALREGISTRATION_C ,incoming.SELECTDEALREP2_C ,incoming.DEALREGID2_C ,incoming.APPLICATION_C ,incoming.OPPORTUNITYLIFETIMEYEARS_C ,incoming.PROJECTDESCRIPTION_C ,incoming.SALESCOMMENT_C ,incoming.PRODUCTMANAGERCOMMENTS ,"
			+ "incoming.HELPSTATUS_C ,incoming.HELPNEEDEDFROM_C ,incoming.DATEOFHELPREQUEST_C ,incoming.CRITICALACTIONITEMSMILESTONES ,incoming.RISKCHALLENGES_C ,incoming.DESIGNINREGIONALMGRAPPROVED_C ,incoming.DESIGNINREGIONALMGRAPPROVALDT ,incoming.DESIGNWINREGIONALMGRAPPROVED ,"
			+ "incoming.DESIGNWINREGIONALMGRAPPROVALDT ,incoming.DESIGNWINVPSALESAPPROVED_C ,incoming.DESIGNWINVPSALESAPPROVALDATE ,incoming.DESIGNWINMARKETINGAPPROVED_C ,incoming.DESIGNWINMARKETINGAPPROVALDATE ,incoming.MPVPSALESAPPROVED_C ,incoming.MPVPSALESAPPROVALDATE_C ,"
			+ "incoming.LOSTVPSALESAPPROVED_C ,incoming.LOSTVPSALESAPPROVALDATE_C ,incoming.PART_C ,incoming.BU_C ,incoming.ANNUALUNITVOLUME_C ,incoming.ASP_C ,incoming.ANNUALREVENUE ,incoming.EXPECTEDREVENUE_C ,incoming.LASTUPDATEDBY ,incoming.LASTUPDATEDATE ,incoming.PRODUCTTYPE )";

	private static final String QUERY_INSERT_REVENUE = "MERGE INTO XXINV_REVENUE a "
			+ "USING (SELECT ? REVNID,? BUORGID,? COSTAMOUNT,? DOWNSIDEAMOUNT,? EXPECTAMOUNT,? MARGINAMOUNT,? OPTYID,? UNITPRICE,? QUANTITY,? REVNAMOUNT "
			+ ",? REVNAMOUNTCURCYCODE,? UPSIDEAMOUNT,? PARTYNAME,? DESCRIPTION,? NAME,? REVNNUMBER,? STATUSCODE,? EFFECTIVEDATE,? ACTUALCLOSEDATE,? ATTACHMENTENTITYNAME "
			+ ",? ITEMNUMBER,? ITEMNUMBERINTERNAL,? OPTYNUMBER,? PRODUCTTYPE,? SALESCHANNELCD,? REVNLINETYPECODE,? SALESACCOUNTUNIQUENAME,? BU_C,? ASP_C,"
			+ "? ANNUALUNITVOLUME_C,? EXPECTEDREVENUE_C,? BUOWNERNAME_C,? OPPORTUNITYSALESSTAGE_C,? ASPCUSTOM_C,? PRODUCT_ID_C,? PRODUCT_C,? PART_ID_C,? PART_C from dual)"
			+ " incoming ON (a.REVNID = incoming.REVNID ) " + "WHEN MATCHED THEN " + "UPDATE SET "
			+ "a.BUORGID=incoming.BUORGID,a.COSTAMOUNT=incoming.COSTAMOUNT,a.DOWNSIDEAMOUNT=incoming.DOWNSIDEAMOUNT,a.EXPECTAMOUNT=incoming.EXPECTAMOUNT,"
			+ "a.MARGINAMOUNT=incoming.MARGINAMOUNT,a.OPTYID=incoming.OPTYID,a.UNITPRICE=incoming.UNITPRICE,a.QUANTITY=incoming.QUANTITY,"
			+ "a.REVNAMOUNT=incoming.REVNAMOUNT,a.REVNAMOUNTCURCYCODE=incoming.REVNAMOUNTCURCYCODE,a.UPSIDEAMOUNT=incoming.UPSIDEAMOUNT,"
			+ "a.PARTYNAME=incoming.PARTYNAME,a.DESCRIPTION=incoming.DESCRIPTION,a.NAME=incoming.NAME,a.REVNNUMBER=incoming.REVNNUMBER,"
			+ "a.STATUSCODE=incoming.STATUSCODE,a.EFFECTIVEDATE=incoming.EFFECTIVEDATE,a.ACTUALCLOSEDATE=incoming.ACTUALCLOSEDATE, "
			+ "a.ATTACHMENTENTITYNAME=incoming.ATTACHMENTENTITYNAME,a.ITEMNUMBER=incoming.ITEMNUMBER,a.ITEMNUMBERINTERNAL=incoming.ITEMNUMBERINTERNAL, "
			+ "a.OPTYNUMBER=incoming.OPTYNUMBER,a.PRODUCTTYPE=incoming.PRODUCTTYPE,a.SALESCHANNELCD=incoming.SALESCHANNELCD,a.REVNLINETYPECODE=incoming.REVNLINETYPECODE,"
			+ "a.SALESACCOUNTUNIQUENAME=incoming.SALESACCOUNTUNIQUENAME,a.BU_C=incoming.BU_C,a.ASP_C=incoming.ASP_C,a.ANNUALUNITVOLUME_C=incoming.ANNUALUNITVOLUME_C,"
			+ "a.EXPECTEDREVENUE_C=incoming.EXPECTEDREVENUE_C,a.BUOWNERNAME_C=incoming.BUOWNERNAME_C,a.OPPORTUNITYSALESSTAGE_C=incoming.OPPORTUNITYSALESSTAGE_C,"
			+ "a.ASPCUSTOM_C=incoming.ASPCUSTOM_C,a.PRODUCT_ID_C=incoming.PRODUCT_ID_C,a.PRODUCT_C=incoming.PRODUCT_C,a.PART_ID_C=incoming.PART_ID_C,"
			+ "a.PART_C=incoming.PART_C " + "WHEN NOT MATCHED THEN "
			+ "INSERT (REVNID,BUORGID,COSTAMOUNT,DOWNSIDEAMOUNT,EXPECTAMOUNT,MARGINAMOUNT,OPTYID,UNITPRICE,QUANTITY,REVNAMOUNT,REVNAMOUNTCURCYCODE,UPSIDEAMOUNT,"
			+ "PARTYNAME,DESCRIPTION,NAME,REVNNUMBER,STATUSCODE,EFFECTIVEDATE,ACTUALCLOSEDATE,ATTACHMENTENTITYNAME,ITEMNUMBER,ITEMNUMBERINTERNAL,OPTYNUMBER,PRODUCTTYPE,"
			+ "SALESCHANNELCD,REVNLINETYPECODE,SALESACCOUNTUNIQUENAME,BU_C,ASP_C,ANNUALUNITVOLUME_C,EXPECTEDREVENUE_C,BUOWNERNAME_C,OPPORTUNITYSALESSTAGE_C,ASPCUSTOM_C,"
			+ "PRODUCT_ID_C,PRODUCT_C,PART_ID_C,PART_C) "
			+ "VALUES (incoming.REVNID,incoming.BUORGID,incoming.COSTAMOUNT,incoming.DOWNSIDEAMOUNT,incoming.EXPECTAMOUNT,incoming.MARGINAMOUNT,incoming.OPTYID,incoming.UNITPRICE,incoming.QUANTITY,incoming.REVNAMOUNT,incoming.REVNAMOUNTCURCYCODE,incoming.UPSIDEAMOUNT,"
			+ "incoming.PARTYNAME,incoming.DESCRIPTION,incoming.NAME,incoming.REVNNUMBER,incoming.STATUSCODE,incoming.EFFECTIVEDATE,incoming.ACTUALCLOSEDATE,incoming.ATTACHMENTENTITYNAME,incoming.ITEMNUMBER,incoming.ITEMNUMBERINTERNAL,incoming.OPTYNUMBER,incoming.PRODUCTTYPE,"
			+ "incoming.SALESCHANNELCD,incoming.REVNLINETYPECODE,incoming.SALESACCOUNTUNIQUENAME,incoming.BU_C,incoming.ASP_C,incoming.ANNUALUNITVOLUME_C,incoming.EXPECTEDREVENUE_C,incoming.BUOWNERNAME_C,incoming.OPPORTUNITYSALESSTAGE_C,incoming.ASPCUSTOM_C,"
			+ "incoming.PRODUCT_ID_C,incoming.PRODUCT_C,incoming.PART_ID_C,incoming.PART_C)";
	SalesDashboardUtils salesDashboardUtils = new SalesDashboardUtils();

	@Autowired
	@Qualifier("secondaryDataSource")
	private DataSource secondaryDataSource;

	@Autowired
	@Qualifier("batchDatasource")
	public DataSource batchDatasource;

	

	@Override
	public void write(List<? extends Opportunity> items) throws Exception {

		LOGGER.debug("Write to database: ");
		JdbcBatchItemWriter<Opportunity> databaseItemWriter = new JdbcBatchItemWriter<>();
		databaseItemWriter.setDataSource(secondaryDataSource);
		databaseItemWriter.setSql(QUERY_INSERT_OPPORTUNITY);
		ItemPreparedStatementSetter<Opportunity> opPreparedStatementSetter = new OppPreparedStatementSetter();

		databaseItemWriter.setItemPreparedStatementSetter(opPreparedStatementSetter);

		databaseItemWriter.write(items);
		LOGGER.debug("Completed In DB Writer" + items.size());
		for (Opportunity opp : items) {

			JdbcBatchItemWriter<Revenue> databaseItemWriter1 = new JdbcBatchItemWriter<>();
			databaseItemWriter1.setDataSource(secondaryDataSource);

			databaseItemWriter1.setSql(QUERY_INSERT_REVENUE);
				ItemPreparedStatementSetter<Revenue> revPreparedStatementSetter = new RevenuePreparedStatementSetter();
			databaseItemWriter1.setItemPreparedStatementSetter(revPreparedStatementSetter);

			databaseItemWriter1.write(opp.getChildRevenue());
			LOGGER.debug("Completed In DB Writer revenue");
		}

	}

	@Override
	public void beforeStep(StepExecution stepExecution) {
		

	}

	@Override
	public ExitStatus afterStep(StepExecution stepExecution) {
		LOGGER.debug("SOAPOpportunity job completed successfully");
		if (stepExecution.getStatus() == BatchStatus.COMPLETED) {
			LOGGER.info("SOAPOpportunity job completed successfully");
			salesDashboardUtils.setInterfacePoolDateTime("soapOpportunityDBJob", batchDatasource);

		}

		return null;
	}

}
